#ifndef SERVER_COMMAND_H
#define SERVER_COMMAND_H


#include "ServerIncludes.h"
#include <iostream>

enum ServerProtocol : int
{
	CS_CLOSE_GAME,
	CS_LOGIN_PLAYER,
	CS_LOGOUT_PLAYER,
	CS_REFRESH_GAMES,
	CS_JOIN_GAME,
	CS_CREATE_GAME,
	CS_LEAVE_GAME,
	CS_DISBAND_GAME,
	CS_JOIN_TEAM,
	CS_READY_STATUS,
	CS_BENCH_PLAYER,
	CS_SET_GAMEPLAY_OPTIONS,
	CS_SEND_MSG_PARTY,
	CS_SEND_MSG_TEAM,
	CS_SEND_MSG_LOBBY,
	CS_SEND_WHISPER,
	CS_SEND_PARTY_MSG,
	CS_KICK_PLAYER,
	CS_PAUSE_GAME,
	CS_END_GAME,
	CS_RESUME_GAME,
	CS_QUIT_GAME,
	CS_PLACE_TOWER,
	CS_SUMMON_MINION,
	CS_RESEARCH_MINION,
	CS_RESEARCH_TOWER,

	SC_LOGIN_PLAYER,
	SC_REFRESH_GAMES,
	SC_JOIN_GAME,
	SC_CREATE_GAME,
	SC_DISBAND_GAME,
	SC_JOIN_TEAM,
	SC_BENCH_PLAYER,
	SC_UPDATE_LOBBY,
	SC_SEND_MESSAGE,
	SC_PAUSE_GAME,
	SC_END_GAME,
	SC_RESUME_GAME,
	SC_QUIT_GAME,
	SC_SUMMON_MINION,
	SC_PLACE_TOWER,
	SC_UPDATE_ECONOMY,
	SC_UPDATE_BASE_HP,
	SC_ASSIGN_RESOURCE_NODE,
	SC_RESEARCH_MINION,
	SC_RESEARCH_TOWER,

	IS_PLACE_TOWER_BC,
	IS_ADJUST_ZOI,
	IS_SUMMON_MINION_BC,
	IS_UPDATE_MINION_LIST,
	IS_UPDATE_TOWERLISTS,
	IS_UPDATE_PROJECTILES,
	IS_UPDATE_ECONOMY
};


class ServerCommand
{
private: 
	void *data;
	ServerProtocol command;

public:
	ServerCommand();
	ServerCommand(void* _data, ServerProtocol _command) : data(_data), command(_command) { printf("\nServerCommand Initialized as type: %i", _command); };
	~ServerCommand();

	void Execute();
};
#endif